# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xci
# IP: The module: 'xdma_ddr_rst_mig_7series_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xci
# IP: The module: 'xdma_ddr_rst_mig_7series_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/my_work/QT7013/0_OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_rst_mig_7series_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
