# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1.xci
# IP: The module: 'xdma_ddr_util_ds_buf_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_util_ds_buf_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_util_ds_buf_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1.xci
# IP: The module: 'xdma_ddr_util_ds_buf_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_util_ds_buf_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_ddr_util_ds_buf_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
