# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pcie.xdc

# Block Designs: bd/xdma_ddr/xdma_ddr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr || ORIG_REF_NAME==xdma_ddr} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/xdma_ddr_xdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_xdma_0_0 || ORIG_REF_NAME==xdma_ddr_xdma_0_0} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_util_ds_buf_1 || ORIG_REF_NAME==xdma_ddr_util_ds_buf_1} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_axi_bram_ctrl_0_0/xdma_ddr_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_axi_bram_ctrl_0_0 || ORIG_REF_NAME==xdma_ddr_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_blk_mem_gen_0_0/xdma_ddr_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_blk_mem_gen_0_0 || ORIG_REF_NAME==xdma_ddr_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_mig_7series_0_0/xdma_ddr_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_mig_7series_0_0 || ORIG_REF_NAME==xdma_ddr_mig_7series_0_0} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/xdma_ddr_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_axi_smc_0 || ORIG_REF_NAME==xdma_ddr_axi_smc_0} -quiet] -quiet

# IP: bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_ddr_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==xdma_ddr_rst_mig_7series_0_100M_0} -quiet] -quiet

# XDC: bd/xdma_ddr/xdma_ddr_ooc.xdc
