# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modelsim_2020.4/win64
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.cache/wt [current_project]
set_property parent.project_path E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/hdl/xdma_ddr_wrapper.v
add_files E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/xdma_ddr.bd
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_0/source/xdma_ddr_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_0/synth/xdma_ddr_xdma_0_0_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/xdma_ddr_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/source/xdma_ddr_xdma_0_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_xdma_0_0/synth/xdma_ddr_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_util_ds_buf_1/xdma_ddr_util_ds_buf_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_bram_ctrl_0_0/xdma_ddr_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_blk_mem_gen_0_0/xdma_ddr_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_mig_7series_0_0/xdma_ddr_mig_7series_0_0/user_design/constraints/xdma_ddr_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_mig_7series_0_0/xdma_ddr_mig_7series_0_0/user_design/constraints/xdma_ddr_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_1/bd_eb0a_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_1/bd_eb0a_psr0_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_2/bd_eb0a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_2/bd_eb0a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_3/bd_eb0a_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_3/bd_eb0a_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_7/bd_eb0a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_8/bd_eb0a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_9/bd_eb0a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_10/bd_eb0a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_11/bd_eb0a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_12/bd_eb0a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/bd_0/ip/ip_13/bd_eb0a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/ip/xdma_ddr_rst_mig_7series_0_100M_0/xdma_ddr_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/sources_1/bd/xdma_ddr/xdma_ddr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/constrs_1/new/pcie.xdc
set_property used_in_implementation false [get_files E:/my_work/QT7013/vivado2019/OK/ddr_xdam_ok/ddr_xdam_ok.srcs/constrs_1/new/pcie.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xdma_ddr_wrapper -part xc7z100ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xdma_ddr_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xdma_ddr_wrapper_utilization_synth.rpt -pb xdma_ddr_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
